# Generated by Django 6.0.1 on 2026-01-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='الرقم الوطني أو رقم الهوية/الجواز'),
        ),
        migrations.AlterField(
            model_name='smartscreen',
            name='screen_token',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('TEACHER', 'Teacher'), ('MANAGER', 'schoolmanager'), ('SUPER_ADMIN', 'Super Admin')], max_length=20),
        ),
    ]
