# Generated by Django 6.0.1 on 2026-02-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_pickuprequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentschool',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('REQUESTED', 'Requested'), ('AT_GATE', 'At Gate'), ('DELIVERED', 'Delivered')], db_index=True, default='PRESENT', max_length=20),
        ),
        migrations.CreateModel(
            name='ClassSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.schoolclass')),
            ],
            options={
                'verbose_name': 'تسلسل طلاب الفصل',
                'unique_together': {('school', 'school_class')},
            },
        ),
    ]
