# Generated by Django 6.0.1 on 2026-02-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_parentschool_is_approved_and_more'),
    ]

    operations = [
    ]
import re
from django.db import migrations, models

def sync_class_sequences(apps, schema_editor):
    # جلب النماذج من الحالة الحالية لـ Migration
    Student = apps.get_model('attendance', 'Student')
    ClassSequence = apps.get_model('attendance', 'ClassSequence')
    SchoolClass = apps.get_model('attendance', 'SchoolClass')

    for school_class in SchoolClass.objects.all():
        # 1. جلب كل الطلاب في هذا الفصل
        students = Student.objects.filter(school_class=school_class)
        
        max_num = 0
        for student in students:
            if student.student_code:
                # استخراج الرقم من نهاية الكود (مثال: SCH1-CLS3-0015 -> نأخذ 15)
                # نستخدم Regex للبحث عن آخر مجموعة أرقام في الكود
                match = re.search(r'(\d+)$', student.student_code)
                if match:
                    num = int(match.group(1))
                    if num > max_num:
                        max_num = num

        # 2. إنشاء أو تحديث سجل التسلسل لهذا الفصل
        ClassSequence.objects.update_or_create(
            school=school_class.school,
            school_class=school_class,
            defaults={'last_number': max_num}
        )

def reverse_sync(apps, schema_editor):
    # في حال التراجع عن Migration (اختياري)
    ClassSequence = apps.get_model('attendance', 'ClassSequence')
    ClassSequence.objects.all().delete()

