# Generated by Django 6.0.1 on 2026-02-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_migrate_sequences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name': 'School Class', 'verbose_name_plural': 'School Classes'},
        ),
    ]
